### ISSUE TITLE
Header image submission for relayer registry

### ISSUE THREAD

**Issue by BMillman19** [0xProject/0x-relayer-registry#3]
@burnsben to provide guidance on header image specs

**Comment by burnsben** [comment]
thumbnail dimensions: 216x128px

**Comment by tomhschmidt** [comment]
Gonna re-open this until the PR is in to add the screenshot spec. I also think we should maybe increase the resolution a bit so that we have room to use it for other use cases? (maybe 2x or 3x)

What do you think @burnsben?

**Comment by burnsben** [comment]
@tomhschmidt Good catch. We can always scale down. Let's go with 648x384px
