### ISSUE TITLE
Introduce identifier for relayers

### ISSUE THREAD

**Issue by cbovis** [0xProject/0x-relayer-registry#31]
I’m interested in integrating the Relayer Registry with 0x Tracker however one of the things holding me back is the lack of an identifier associated with relayers. This prevents me from associating fills with a relayer. Name can be used but is susceptible to change if a relayer rebrands.

I propose adding a new id field to each relayer with a randomly generated uuid value. This uuid should never change once it has been set.

**Comment by tomhschmidt** [comment]
Yeah, this was something I regret not adding to start :P 

I anticipated a lot more people adding a lot more relayers, and asking everyone to generate UUIDs seemed like a pain, but agreed that the lack of an index is becoming a pain.

Are you envisioning keeping this as an array with an id field, or changing this from an array to a map with the UUID as the key? Latter might be more convenient.

**Comment by cbovis** [comment]
Agreed the latter would be more convenient but may break some things for people who pull the relayer list directly from the repo... I'd personally be content with an id prop added to each relayer in the existing array. 

Perhaps going forward it would make sense to publish the list as an NPM package? This would help with versioning, changing from an array to ID-keyed object would be a major release. For anyone not in the NPM ecosystem they would still be able to pull from the repository via a tagged branch if they want safety from breaking changes.

**Comment by fabioberger** [comment]
Really like this idea @cbovis. Should be easy enough for us to publish the list an an NPM package. Will bring it up in our next sprint planning.

**Comment by tomhschmidt** [comment]
I'd be down to rip the bandaid off and just convert the registry to a map of UUIDs to relayer info. I don't think that many people are using it right now, and I'd rather make the change now while switching costs are low.

+1 to npm idea too :)

**Comment by tomhschmidt** [comment]
Resolved with #33 @cbovis
